services:
  influxdb:
    container_name: influxdb
    image: unless-stopped
    restart: unless-stopped
    volumes:
      - ./influx/config.yml:/etc/influxdb2/config.yml
      - ./influx/data:/var/lib/influxdb2
    ports:
      - 8086:8086

  grafana:
    container_name: grafana
    image: grafana/grafana
    restart: unless-stopped
    user: '0'
    volumes:
      - ./grafana:/var/lib/grafana
    ports:
      - 3000:3000
